<a href="https://colab.research.google.com/github/PragadeshBS/Deep-Learning/blob/main/SequencePredictionLSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

In [24]:
def splitSequence(seq, n_steps):
    
    #Declare X and y as empty list
    X = []
    y = []
    
    for i in range(len(seq)):
        #get the last index
        lastIndex = i + n_steps
        
        #if lastIndex is greater than length of sequence then break
        if lastIndex > len(seq) - 1:
            break
            
        #Create input and output sequence
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        
        #append seq_X, seq_y in X and y list
        X.append(seq_X)
        y.append(seq_y)
    #Convert X and y into numpy array
    X = np.array(X)
    y = np.array(y)
    
    return X,y 

In [25]:
n_steps = 5
data = [10*i for i in range(1, 20)]
X, y = splitSequence(data, n_steps = 5)

In [26]:
X

array([[ 10,  20,  30,  40,  50],
       [ 20,  30,  40,  50,  60],
       [ 30,  40,  50,  60,  70],
       [ 40,  50,  60,  70,  80],
       [ 50,  60,  70,  80,  90],
       [ 60,  70,  80,  90, 100],
       [ 70,  80,  90, 100, 110],
       [ 80,  90, 100, 110, 120],
       [ 90, 100, 110, 120, 130],
       [100, 110, 120, 130, 140],
       [110, 120, 130, 140, 150],
       [120, 130, 140, 150, 160],
       [130, 140, 150, 160, 170],
       [140, 150, 160, 170, 180]])

In [27]:
y

array([ 60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170, 180,
       190])

In [28]:
for i in range(len(X)):
    print(X[i], y[i])

[10 20 30 40 50] 60
[20 30 40 50 60] 70
[30 40 50 60 70] 80
[40 50 60 70 80] 90
[50 60 70 80 90] 100
[ 60  70  80  90 100] 110
[ 70  80  90 100 110] 120
[ 80  90 100 110 120] 130
[ 90 100 110 120 130] 140
[100 110 120 130 140] 150
[110 120 130 140 150] 160
[120 130 140 150 160] 170
[130 140 150 160 170] 180
[140 150 160 170 180] 190


In [29]:
# reshape from [samples, timesteps] into [samples, timesteps, features]

n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
X[:2]

array([[[10],
        [20],
        [30],
        [40],
        [50]],

       [[20],
        [30],
        [40],
        [50],
        [60]]])

In [30]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [31]:
model = tf.keras.Sequential()
model.add(layers.LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(layers.Dense(1))

In [32]:
model.layers

In [33]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_1 (LSTM)               (None, 50)                10400     
                                                                 
 dense_1 (Dense)             (None, 1)                 51        
                                                                 
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.01),
loss=tf.keras.losses.MeanSquaredError(), metrics=['accuracy'])

In [35]:
model.fit(X, y, epochs=200, verbose=1)

Epoch 1/200
1/1 [==============================] - 1s 1s/step - loss: 19051.6816 - accuracy: 0.0000e+00
Epoch 2/200
1/1 [==============================] - 0s 13ms/step - loss: 17471.8457 - accuracy: 0.0000e+00
Epoch 3/200
1/1 [==============================] - 0s 12ms/step - loss: 16731.1465 - accuracy: 0.0000e+00
Epoch 4/200
1/1 [==============================] - 0s 10ms/step - loss: 16310.2295 - accuracy: 0.0000e+00
Epoch 5/200
1/1 [==============================] - 0s 13ms/step - loss: 15758.0996 - accuracy: 0.0000e+00
Epoch 6/200
1/1 [==============================] - 0s 9ms/step - loss: 13160.9297 - accuracy: 0.0000e+00
Epoch 7/200
1/1 [==============================] - 0s 11ms/step - loss: 197.2612 - accuracy: 0.0000e+00
Epoch 8/200
1/1 [==============================] - 0s 8ms/step - loss: 788.0084 - accuracy: 0.0000e+00
Epoch 9/200
1/1 [==============================] - 0s 8ms/step - loss: 162.8200 - accuracy: 0.0000e+00
Epoch 10/200
1/1 [==============================] - 0s 8m

In [36]:
test_data = np.array([90, 100, 110, 120, 130])
test_data = test_data.reshape((1, n_steps, n_features))
test_data

array([[[ 90],
        [100],
        [110],
        [120],
        [130]]])

In [37]:
predictNextNumber = model.predict(test_data, verbose=1)
print(predictNextNumber)

1/1 [==============================] - 0s 158ms/step
[[140.14568]]
